language: c

sudo: required

addons:
    apt:
        packages:
            - gperf
            - elfutils
            - zlib1g-dev
            - mingw32
            - mingw32-binutils
            - clang    # scan-build

os:
    - linux

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: gcc
          env: CUDA=5.5-54
        - os: linux
          compiler: gcc
          env: CUDA=6.5-19
        - os: linux
          compiler: gcc
          env: CUDA=7.0-28
        - os: linux
          compiler: gcc
          env: CUDA=7.5-18
        - os: linux
          compiler: gcc
          env: CUDA=8.0.61-1
        - os: linux
          compiler: gcc
          env: CUDA=9.0.176-1 CUDA_REPO=xenial
        - os: linux
          compiler: gcc
          env: CUDA=9.1.85-1 CUDA_REPO=xenial

    exclude:
        - os: osx
          compiler: gcc

before_install:
    - source ./.travis/install_cuda.sh

script:
    - ./autogen.sh
    - ./configure $HOST
    - make
    - make ${TEST:-test}
