language: c

sudo: required

addons:
    apt:
        packages:
            - gperf
            - elfutils
            - zlib1g-dev
            - mingw32
            - mingw32-binutils
            - clang    # scan-build

os:
    - linux

matrix:
    include:
        - os: linux
          compiler: gcc
          env: CUDA=5.5
        - os: linux
          compiler: gcc
          env: CUDA=6.5
        - os: linux
          compiler: gcc
          env: CUDA=7.0
        - os: linux
          compiler: gcc
          env: CUDA=7.5
        - os: linux
          compiler: gcc
          env: CUDA=8.0
        - os: linux
          compiler: gcc
          env: CUDA=9.0
        - os: linux
          compiler: gcc
          env: CUDA=9.1

before_install:
    - source ./.travis/install_cuda.sh

script:
    - ./autogen.sh
    - ./configure $HOST
    - make
    - make ${TEST:-test}
